### ISSUE TITLE
documentation wrong

### ISSUE THREAD

**Issue by adamf663** [sangoma/pysensu#7]
there is no pysensu.api and there is no pysensu.api.SensuAPI

**Comment by angvp** [comment]
Hello @adamf663 are you trying to use pysensu with python3 by any chance?

**Comment by adamf663** [comment]
Yup.  I found a forked repo with correct instructions.    
It's @ my work pc;  I can toss you the docs if they weren't from your repo.

----- Original Message -----

**Comment by angvp** [comment]
@adamf663 There are not forked repo with different instructions, you're probably using pysensu not pysensu-ng

**Comment by adamf663** [comment]
pk.  thanks!

----- Original Message -----
