### ISSUE TITLE
Bug on bad request status

### ISSUE THREAD

**Issue by zopar** [sangoma/pysensu#9]
Hi,
I tried to make a query with a client that does not exists and I have this error in
``
API pysensu/api.py", line 59, in _request
    elif resp.status_code.startswith('400'):
AttributeError: 'int' object has no attribute 'startswith'
``

This is because the resp.status.code is an integer, so or we change it to str and use starswith
``
   elif str(resp.status_code).startswith('400'):
``
or we can use
``
   elif resp.status_code == 400:
``

Just to understand: why you distinguish 400 from other errors?
Maybe, do you want a different exception messages for all the 40* errors?
If so we need the startswith but with only 40 and not 400:
``
    elif str(resp.status_code).startswith('40'):
``

If we decide how we want to proceed and manage 40* errors, I could write the related code and send a merge requests .

**Comment by angvp** [comment]
PR will be accepted (to handle more 40X cases) At the moment I wrote the main code if I remember correctly the only 4XX error the SensuAPI had was 400 this might have changed with the time .. do a PR and I will review it and accept it.
